# Generated by Django 4.1.7 on 2023-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='sender',
        ),
        migrations.AddField(
            model_name='thread',
            name='is_one_to_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(to='user.userprofile'),
        ),
    ]
